# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master
name: 0.1$(Rev:.r)
pool:
  vmImage: "windows-latest"

variables:
  solution: "AmortizationCalculator.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "3.1.x"
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "SonarCloud"
      organization: "jacksondr5"
      scannerMode: "MSBuild"
      projectKey: "260209af2fab44121dc70bdfece4612df5f941ac"
      projectName: "amortization-calculator"
      projectVersion: $(Build.BuildNumber)
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: "restore"
      projects: $(solution)
      feedsToUse: "select"
      verbosityRestore: "Normal"
  - task: DotNetCoreCLI@2
    displayName: Build Solution
    inputs:
      command: "build"
      projects: $(solution)
      arguments: "-c $(buildConfiguration) --no-restore --nologo"
  - task: DotNetCoreCLI@2
    displayName: Publish Web Project
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "-c $(buildConfiguration) --no-restore --nologo -o ./WebDeploy"
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: "test"
      projects: $(solution)
      arguments: "--nologo --no-build -c $(buildConfiguration) -s ./UnitTest.runsettings"
  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "Pay-As-You-Go(34a85b0b-7284-4a31-8122-8e32ba39a46c)"
      appType: "webAppLinux"
      WebAppName: "j5-amortization-calculator"
      packageForLinux: "$(System.DefaultWorkingDirectory)/**/*.zip"
      RuntimeStack: "DOTNETCORE|3.1"
